using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace UtilityBelt.Lib.Salvage {
    public enum Material {
        CERAMIC = 1,
        PORCELAIN = 2,
        CLOTH = 3,
        LINEN = 4,
        SATIN = 5,
        SILK = 6,
        VELVET = 7,
        WOOL = 8,
        GEM = 9,
        AGATE = 10,
        AMBER = 11,
        AMETHYST = 12,
        AQUAMARINE = 13,
        AZURITE = 14,
        BLACK_GARNET = 15,
        BLACK_OPAL = 16,
        BLOODSTONE = 17,
        CARNELIAN = 18,
        CITRINE = 19,
        DIAMOND = 20,
        EMERALD = 21,
        FIRE_OPAL = 22,
        GREEN_GARNET = 23,
        GREEN_JADE = 24,
        HEMATITE = 25,
        IMPERIAL_TOPAZ = 26,
        JET = 27,
        LAPIS_LAZULI = 28,
        LAVENDER_JADE = 29,
        MALACHITE = 30,
        MOONSTONE = 31,
        ONYX = 32,
        OPAL = 33,
        PERIDOT = 34,
        RED_GARNET = 35,
        RED_JADE = 36,
        ROSE_QUARTZ = 37,
        RUBY = 38,
        SAPPHIRE = 39,
        SMOKEY_QUARTZ = 40,
        SUNSTONE = 41,
        TIGER_EYE = 42,
        TOURMALINE = 43,
        TURQUOISE = 44,
        WHITE_JADE = 45,
        WHITE_QUARTZ = 46,
        WHITE_SAPPHIRE = 47,
        YELLOW_GARNET = 48,
        YELLOW_TOPAZ = 49,
        ZIRCON = 50,
        IVORY = 51,
        LEATHER = 52,
        ARMOREDILLO_HIDE = 53,
        GROMNIE_HIDE = 54,
        REEDSHARK_HIDE = 55,
        METAL = 56,
        BRASS = 57,
        BRONZE = 58,
        COPPER = 59,
        GOLD = 60,
        IRON = 61,
        PYREAL = 62,
        SILVER = 63,
        STEEL = 64,
        STONE = 65,
        ALABASTER = 66,
        GRANITE = 67,
        MARBLE = 68,
        OBSIDIAN = 69,
        SANDSTONE = 70,
        SERPENTINE = 71,
        WOOD = 72,
        EBONY = 73,
        MAHOGANY = 74,
        OAK = 75,
        PINE = 76,
        TEAK = 77,
    }
}

