variables:
  NUGET_PATH: 'C:\Tools\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\msbuild.exe'
  VSTEST_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe'
  NSIS_PATH: 'C:\Program Files (x86)\NSIS\makensis.exe'
  HUGO_PATH: 'C:\Tools\hugo.exe'
  CURL_PATH: 'C:\Tools\curl.exe'
  INSTALLER_PATH: '.\Installer\Install.nsi'
  BUILD_PATH: '.\bin'
  STAGING_URL: 'https://ubstaging.surge.sh'
  DATA_URL: 'https://ubdata.surge.sh'
  WEB_PATH: 'C:\UtilityBelt\www\'

stages:
  - build
  - test
  - deploy staging

build:
  stage: build
  script:
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" -target:Clean'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly'
    - '& "$env:NSIS_PATH" "$env:INSTALLER_PATH"'
  artifacts:
    expire_in: 30 days
    paths:
      - '$env:BUILD_PATH\'

test:
  stage: test
  script:
    - '& "$env:VSTEST_PATH" "$env:BUILD_PATH\tests\UBLoader.Tests.dll"'
    - '& "$env:VSTEST_PATH" "$env:BUILD_PATH\tests\UtilityBelt.Tests.dll"'

deploy staging:
  stage: deploy staging
  script:
    - '$env:UB_INSTALLER = "$env:BUILD_PATH\" + (Get-ChildItem $env:BUILD_PATH\UtilityBeltInstaller*.exe).Name'
    - '$env:UB_INSTALLER_OUT = ".\public\$env:CI_COMMIT_REF_NAME\" + (Get-ChildItem $env:BUILD_PATH\UtilityBeltInstaller*.exe).Name'
    - 'Remove-Item -Force ".\public" -Recurse -ErrorAction Ignore; echo 1'
    - '& "$env:BUILD_PATH\ubdocsgen\UBDocsGen.exe" "$env:CI_COMMIT_REF_NAME"'
    - '& "$env:HUGO_PATH" --themesDir .\Site\themes\ --destination ".\public\$env:CI_COMMIT_REF_NAME\" --baseURL $env:STAGING_URL/$env:CI_COMMIT_REF_NAME/'
    - 'Remove-Item -Force "C:\UtilityBelt\www\$env:CI_COMMIT_REF_NAME" -Recurse -ErrorAction Ignore; echo 1'
    - 'Copy-Item -Path ".\public\*" -Destination "$env:WEB_PATH" -Recurse'
    - 'python .\scripts\clean-and-generate-staging-index.py'
    - 'surge --domain $env:STAGING_URL $env:WEB_PATH'
  artifacts:
    expire_in: 30 days
    paths:
      - '.\public\$env:CI_COMMIT_REF_NAME\'
  except:
    - release

pages:
  stage: .post
  script:
  - 'Remove-Item -Force ".\public" -Recurse -ErrorAction Ignore; echo 1'
  - '& "$env:BUILD_PATH\ubdocsgen\UBDocsGen.exe"'
  - '& "$env:HUGO_PATH" --themesDir .\Site\themes\'
  artifacts:
    paths:
    - public
  only:
  - tags
